"""
==========================================
GenerativeAURORA - NSRDB Merge and Inspect
==========================================

PURPOSE
-------
This script combines the individual NSRDB CSV files downloaded by
`download_nsrdb.py` into a single clean dataset for the GenerativeAURORA
modeling pipeline.

WHAT THIS DOES
--------------
    1. Loads all 25 CSV files from nsrdb_data/
    2. Standardizes column names to uppercase (matches Gemini download script)
    3. Re-computes clearness index and sky regime if missing
    4. Filters to daytime hours only (GHI > 0 and solar zenith < 90)
    5. Saves merged clean dataset as nsrdb_merged.parquet
    6. Prints summary stats per site

WORKFLOW POSITION
-----------------
This is the SECOND data-processing step in the GenerativeAURORA pipeline. 
Thus, run this after all 25 CSV files are downloaded / after the 'download_nsrdb.py' file has completed.

DATA STANDARDIZATION
--------------------
All input column names are:
    - converted to strings,
    - stripped of leading/trailing whitespace, and
    - converted to uppercase.

For example:
    "GHI"       -> "GHI"
    "Year"      -> "YEAR"
    "Site Name" -> "SITE NAME"

This provides consistent column naming across all downloaded files and
simplifies downstream processing.

DERIVED VARIABLES
-----------------
The script ensures that two variables required by the GenerativeAURORA
pipeline are available.

1. Clearness Index

   If `CLEARNESS_INDEX` is not already present, it is calculated as:

       Clearness Index = GHI / Clearsky GHI

   Values are clipped to the range [0, 1].

2. Sky Regime

   If `SKY_REGIME` is not already present, observations are classified as:

       Clearness Index <= 0.10        -> Overcast
       0.10 < Clearness Index <= 0.35 -> Cloudy
       Clearness Index > 0.35         -> Clear

MAIN FUNCTIONS
--------------
The script is organized into six main functions.
1. load_all_files()
2. ensure_regime_columns(df)
3. filter_daytime(df)
4. build_datetime_index(df)
5. print_summary(df)
6. save_summary(df)

REQUIREMENTS
------------
Install the required Python packages before running:

    pip install pandas pyarrow

`pyarrow` is required because the cleaned dataset is saved in Parquet format.

HOW TO RUN
----------
Run this script from the project directory:

    python merge_nsrdb.py

Make sure `nsrdb_data/` contains the downloaded NSRDB CSV files before
running the script.

IMPORTANT
---------
If the expected 25 files are not available, the script will process only
the CSV files currently present in `nsrdb_data/`. Therefore, verify the
download count before using the resulting dataset for model training.

NEXT STEP
---------
After this script completes successfully, run:

    python eda_nsrdb.py

The EDA script will examine the distributions and characteristics of the
merged daytime dataset before sequence construction and model training.
"""

# =============================================================================
# 1. IMPORTS
# =============================================================================
import os
import glob
import json
import pandas as pd

# =============================================================================
# 2. CONFIGURATION
# =============================================================================

# Directory containing the raw NSRDB CSV files generated by 'download_nsrdb.py'.
DATA_DIR      = "nsrdb_data"

# Main cleaned dataset used by downstream GenerativeAURORA scripts and summary of the merged dataset.
OUTPUT_PARQUET = "nsrdb_merged.parquet"
SUMMARY_FILE   = "nsrdb_summary.json"

# Five site locations expected in the NSRDB dataset.
SITES = [
    "Phoenix_AZ",
    "LosAngeles_CA",
    "Denver_CO",
    "Miami_FL",
    "Seattle_WA",
]

# Study periods
YEARS = [2018, 2019, 2020, 2021, 2022]

# =============================================================================
# 3. INPUT VALIDATION
# =============================================================================
def validate_input_files():
    """
    Check whether the expected NSRDB site-year files are available.

    Returns
    -------
    list
        List of CSV files found in DATA_DIR.

    Raises
    ------
    FileNotFoundError
        If the input directory does not exist.
    """
    if not os.path.isdir(DATA_DIR):
        raise FileNotFoundError(
            f"Input directory not found: {DATA_DIR}"
        )

    files = sorted(glob.glob(os.path.join(DATA_DIR, "*.csv")))

    expected_count = len(SITES) * len(YEARS)

    print("=== Input validation ===")
    print(f"Expected CSV files : {expected_count}")
    print(f"Found CSV files    : {len(files)}")

    if len(files) != expected_count:
        print(
            f"WARNING: Expected {expected_count} files, "
            f"but found {len(files)}."
        )

    return files

# =============================================================================
# 4. LOAD ALL FILES
# =============================================================================
def load_all_files():
    """
    Load and concatenate the NSRDB CSV files.

    Parameters
    ----------
    files : list
        List of CSV file paths to load.

    Returns
    -------
    pandas.DataFrame or None
        Merged dataset, or None if no files could be loaded.
    """
    files = sorted(glob.glob(os.path.join(DATA_DIR, "*.csv")))
    print("Found " + str(len(files)) + " CSV files in " + DATA_DIR + "/")
    print("")

    dfs = []
    for f in files:
        try:
            df = pd.read_csv(f, encoding="utf-8")

            # Standardize all column names to uppercase and stripped
            df.columns = df.columns.astype(str).str.strip().str.upper()

            fname = os.path.basename(f)
            print("  Loaded " + fname.ljust(30) + " -> " + str(len(df)) + " rows, " + str(len(df.columns)) + " cols")
            dfs.append(df)

        except Exception as e:
            print("  ERROR loading " + f + ": " + str(e))

    if not dfs:
        print("No files loaded. Check that nsrdb_data/ folder exists and contains CSV files.")
        return None

    merged = pd.concat(dfs, ignore_index=True)
    print("")
    print("Total rows before filtering: " + str(len(merged)))
    return merged

# =============================================================================
# 5. REGIME PROCESSING
# =============================================================================
def ensure_regime_columns(df):
    """
    Ensure that clearness index and sky-regime variables are available.

    The clearness index (CI) is calculated from global horizontal irradiance
    (GHI) and clearsky GHI:

        CI = GHI / Clearsky GHI

    The resulting CI is clipped to the range [0, 1].

    Sky conditions are then classified using the following thresholds:
        CI <= 0.10         -> Overcast
        0.10 < CI <= 0.35  -> Cloudy
        CI > 0.35          -> Clear

    Existing CLEARNESS_INDEX and SKY_REGIME columns are preserved and are
    only calculated when they are not already present in the input dataset.

    Parameters
    ----------
    df : pandas.DataFrame
        Merged NSRDB dataset containing GHI and Clearsky GHI variables.

    Returns
    -------
    pandas.DataFrame
        Dataset containing CLEARNESS_INDEX and SKY_REGIME columns.
    """
    if "CLEARNESS_INDEX" not in df.columns:
        if "GHI" in df.columns and "CLEARSKY GHI" in df.columns:
            df["CLEARNESS_INDEX"] = (
                df["GHI"] / df["CLEARSKY GHI"].replace(0, float("nan"))
            ).clip(0, 1).fillna(0)
        else:
            print("  WARNING: Cannot compute clearness index. GHI or CLEARSKY GHI missing.")
            df["CLEARNESS_INDEX"] = 0.0

    if "SKY_REGIME" not in df.columns:
        df["SKY_REGIME"] = "Overcast"
        df.loc[df["CLEARNESS_INDEX"] > 0.10, "SKY_REGIME"] = "Cloudy"
        df.loc[df["CLEARNESS_INDEX"] > 0.35, "SKY_REGIME"] = "Clear"

    return df

# =============================================================================
# 6. DAYTIME FILTERING
# =============================================================================
def filter_daytime(df):
    """
    Retain daytime observations for solar-generation modeling.

    An observation is considered daytime when:

        GHI > 0

    If solar zenith angle is available, the additional condition:

        SOLAR ZENITH ANGLE < 90 degrees

    is applied to further exclude nighttime observations.

    The function reports the number and percentage of observations removed
    by the daytime filter.

    Parameters
    ----------
    df : pandas.DataFrame
        Merged NSRDB dataset containing GHI and, optionally, solar zenith
        angle.

    Returns
    -------
    pandas.DataFrame
        Dataset containing daytime observations only.
    """
    before = len(df)

    mask = (df["GHI"] > 0)
    if "SOLAR ZENITH ANGLE" in df.columns:
        mask = mask & (df["SOLAR ZENITH ANGLE"] < 90)

    df_day = df[mask].copy()
    after = len(df_day)
    removed = before - after
    pct = round(100.0 * removed / before, 1) if before > 0 else 0
    print("Daytime filter: kept " + str(after) + " rows, removed " + str(removed) + " nighttime rows (" + str(pct) + "%)")
    return df_day

# =============================================================================
# 7. DATETIME PROCESSING
# =============================================================================
def build_datetime_index(df):
    """
    Construct a datetime column from NSRDB calendar and time fields.

    The NSRDB dataset provides the temporal information in separate columns:
        YEAR
        MONTH
        DAY
        HOUR

    These fields are combined into a single DATETIME column with hourly
    resolution.

    NSRDB timestamps are interpreted according to the time convention
    provided by the downloaded dataset. The function does not perform
    timezone conversion.

    Parameters
    ----------
    df : pandas.DataFrame
        Dataset containing YEAR, MONTH, DAY, and HOUR columns.

    Returns
    -------
    pandas.DataFrame
        Dataset with an additional DATETIME column when all required
        temporal columns are available.
    """
    time_cols = ["YEAR", "MONTH", "DAY", "HOUR"]
    if all(c in df.columns for c in time_cols):
        df["DATETIME"] = pd.to_datetime(
            df["YEAR"].astype(str) + "-"
            + df["MONTH"].astype(str).str.zfill(2) + "-"
            + df["DAY"].astype(str).str.zfill(2) + " "
            + df["HOUR"].astype(str).str.zfill(2) + ":00:00"
        )
        print("Datetime column built from Year/Month/Day/Hour.")
    else:
        missing = [c for c in time_cols if c not in df.columns]
        print("WARNING: Cannot build datetime. Missing columns: " + str(missing))
    return df

# =============================================================================
# 8. DATASET SUMMARY
# =============================================================================
def print_summary(df):
    """
    Print descriptive statistics for the merged daytime dataset.

    The summary includes:

        - Available dataset columns
        - Number of observations per site
        - GHI statistics for each site
        - Sky-regime distribution by site
        - Clearness-index statistics by site

    This function is intended for interactive data-quality inspection and
    does not modify the input dataset.

    Parameters
    ----------
    df : pandas.DataFrame
        Cleaned daytime NSRDB dataset.
    """
    print("")
    print("=== Columns in merged dataset ===")
    print(str(list(df.columns)))

    print("")
    print("=== Row count per site ===")
    if "SITE_NAME" in df.columns:
        print(df.groupby("SITE_NAME").size().to_string())
    elif "SITE" in df.columns:
        print(df.groupby("SITE").size().to_string())
    else:
        print("No SITE_NAME or SITE column found.")

    print("")
    print("=== GHI stats per site (daytime only, W/m2) ===")
    site_col = "SITE_NAME" if "SITE_NAME" in df.columns else "SITE"
    if site_col in df.columns and "GHI" in df.columns:
        stats = df.groupby(site_col)["GHI"].describe().round(1)
        print(stats.to_string())

    print("")
    print("=== Sky regime distribution per site ===")
    if site_col in df.columns and "SKY_REGIME" in df.columns:
        regime_table = df.groupby([site_col, "SKY_REGIME"]).size().unstack(fill_value=0)
        print(regime_table.to_string())

    print("")
    print("=== Clearness index stats per site ===")
    if site_col in df.columns and "CLEARNESS_INDEX" in df.columns:
        ci_stats = df.groupby(site_col)["CLEARNESS_INDEX"].describe().round(3)
        print(ci_stats.to_string())

# =============================================================================
# 8. SAVE SUMMARY 
# =============================================================================
def save_summary(df):
    """
    Save a machine-readable summary of the merged NSRDB dataset.

    The JSON summary contains:
        a. Total number of observations
        b. List of dataset columns
        c. Number of observations per site
        d. Mean and maximum GHI per site
        d. Mean clearness index per site
        e. Sky-regime counts per site

    The summary is saved to the path specified by SUMMARY_FILE.

    Parameters
    ----------
    df : pandas.DataFrame
        Cleaned daytime NSRDB dataset.

    Returns
    -------
    None
        The summary is written directly to SUMMARY_FILE.
    """
    site_col = "SITE_NAME" if "SITE_NAME" in df.columns else "SITE"
    summary = {
        "total_rows": len(df),
        "columns": list(df.columns),
        "sites": {},
    }
    if site_col in df.columns:
        for site, grp in df.groupby(site_col):
            regime_counts = {}
            if "SKY_REGIME" in grp.columns:
                regime_counts = grp["SKY_REGIME"].value_counts().to_dict()
            summary["sites"][site] = {
                "rows": len(grp),
                "ghi_mean": round(float(grp["GHI"].mean()), 2) if "GHI" in grp.columns else None,
                "ghi_max": round(float(grp["GHI"].max()), 2) if "GHI" in grp.columns else None,
                "clearness_mean": round(float(grp["CLEARNESS_INDEX"].mean()), 3) if "CLEARNESS_INDEX" in grp.columns else None,
                "sky_regime": regime_counts,
            }
    with open(SUMMARY_FILE, "w") as f:
        json.dump(summary, f, indent=2)
    print("Summary saved to " + SUMMARY_FILE)

# =============================================================================
# 9. Main Workflow
# =============================================================================
def main():
    """
    Run the complete NSRDB merging and preprocessing workflow.
    """
    print("GenerativeAURORA - NSRDB Merge Script")
    print("")

    # Step 1: Load all files
    df = load_all_files()
    if df is None:
        return

    # Step 2: Ensure regime columns exist
    df = ensure_regime_columns(df)

    # Step 3: Build datetime index
    df = build_datetime_index(df)

    # Step 4: Filter to daytime only
    df = filter_daytime(df)

    # Step 5: Print summary
    print_summary(df)

    # Step 6: Save merged parquet
    df.to_parquet(OUTPUT_PARQUET, index=False)
    print("")
    print("Merged dataset saved to: " + OUTPUT_PARQUET)
    print("Total rows (daytime): " + str(len(df)))
    print("Total columns       : " + str(len(df.columns)))

    # Step 7: Save JSON summary
    save_summary(df)

    print("")
    print("Done. Next step: run eda_nsrdb.py to visualize distributions.")


if __name__ == "__main__":
    main()
